version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=developmentsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
